name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # dispatchEvent breaks in tests on 16
          node-version: '14'
      - run: npm ci
      - run: npm test
